### PR TITLE
Notification rules

### PR DESCRIPTION
**Pull request by pagerduty-sahoko**

### CODE REVIEW

**Review by pagerduty-shawnmotley — APPROVED** [review]
LGTM

**Comment by jdcumpson** [comment]
LGTM too! :shipit:

**Review by jdcumpson — APPROVED** [review]
Only one nit, the comment line should not exceed 80 chars.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.

**Pull request closed without merging**
